
	.include "LKS/MC_OAM.asm"
	.include "LKS/MC_Joypad.asm"
	.include "LKS/MC_Printf.asm"
	.include "LKS/MC_Load.asm"
	.include "LKS/MC_Clear.asm"
	.include "LKS/MC_BG.asm"
	.include "LKS/MC_DMA.asm"
	.include "LKS/MC_PAL.asm"
	.include "LKS/MC_BULLET.asm"
	.include "LKS/MC_SPRITE.asm"
	.include "LKS/MC_Hitbox.asm"	
	.include "LKS/RAM.asm"
